#cloud-config
package_update: true
package_upgrade: true
fqdn: vmi1332848.contaboserver.net
manage_etc_hosts: true
packages:
  - cloud-guest-utils
  - direnv
  - fzf
  - git
  - gptfdisk
  - httpie
  - lazygit
  - man-db
  - man-pages
  - neovim
  - nodejs
  - radare2
  - ripgrep
  - rsync
  - tmux
  - unzip
  - zip
  - zoxide
  - zsh
timezone: Europe/Berlin
runcmd:
  - sudo growpart /dev/sda 3
  - btrfs filesystem resize max /
write_files:
